client_config_backend: file
client_config_file: /home/pi/ArloDownload/drive/client_secrets.json
client_config:
    client_id: 855863261987-dc9pf6rpqd32auq0n7r8hh261k6u13se.apps.googleusercontent.com
    client_secret: 9UqFQoy8m3ePHQKgbswsru6l

save_credentials: True
save_credentials_backend: file
save_credentials_file: /home/pi/ArloDownload/drive/credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install
